import { Rubik } from "next/font/google";
import "./globals.css";
import React from "react";
import { AppProvider } from "../components/AppContext";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import { Toaster } from "react-hot-toast";

const roboto = Rubik({
  subsets: ["latin"],
  weight: ["500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4 w-screen h-screen flex flex-col">
          <AppProvider>
            <Toaster />

            <Header />

            {children}

            <Footer />
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
